### ISSUE TITLE
Is there a sample server?

### ISSUE THREAD

**Issue by bsmelo** [shamblett/coap#1]
Hello,

Is there a sample server application available? Something I could just run and start sending CoAP Requests with a given client (such as Firefox Copper) and receive back CoAP Responses containing some example resources?

Thanks!
Bruno Melo.

**Comment by shamblett** [comment]
Not yet, I've not completed this project yet, still trying to get back to it.

**Comment by pedromassango** [comment]
Hi everyone. Any update on this?

**Comment by shamblett** [comment]
No immediate plans to do this myself unfortunately.

**Comment by thejoker101** [comment]
FWIW, this page lists a bunch of CoAP implementations in various languages. Firefox Copper (mentioned above) is no longer an option due to Firefox plugin architecture changes (see here https://github.com/mkovatsc/Copper). For me, the node.js implementation was easiest to get running `npm install coap --save`. See here: https://github.com/mcollina/node-coap/ Quite a few really simple examples in there as well to get you up and running quickly.
